logging:
  config: classpath:logback/logback-${spring.profiles.active}.xml

spring:
  profiles:
    active: dev

  sql:
    init:
      encoding: UTF-8
      mode: always
      schema-locations:
        - classpath:sql/permission.sql

  # mysql 配置
  datasource:
    # 数据源/连接池类型
    type: com.alibaba.druid.pool.DruidDataSource
    # 数据库驱动名称
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      # 定义初始连接数
      initialSize: 1
      # 定义最小空闲 minIdle=1
      minIdle: 3
      # 定义最大连接数
      maxActive: 100
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 30000
      # 验证使用的SQL语句
      validationQuery: select 'x'
      # 指明连接是否被空闲连接回收器(如果有)进行检验.如果检测失败,则连接将被从池中去除.
      testWhileIdle: true
      # 借出连接时不要测试，否则很影响性能
      testOnBorrow: false
      # 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      # 指定每个连接上PSCache的大小
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,slf4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      db-type: mysql

  # redis 缓存配置
  cache:
    redis:
      time-to-live: 60s
    type: redis
  redis:
    timeout: 10000ms
    lettuce:
      pool:
        max-active: 10
        max-idle: 100
        min-idle: 5
        max-wait: 10000ms

dark:
  # 线程池
  task:
    pool:
      # 核心线程池大小
      corePoolSize: 100
      # 最大线程数
      maxPoolSize:  300
      # 队列容量
      keepAliveSeconds: 500
      # 活跃时间
      queueCapacity:  50
      enabled: true

  scheduled:
    enabled: true
    pool-size: 20

  # 跨域
  cors:
    # 关闭跨域
    enabled: false

  # 权限
  auth:
    # AES密码加密私钥(Base64加密)
    encryptAESKey: S6UG/Nuyxx+7WONtmqQpSA==
    #JWT认证加密私钥(Base64加密)
    encryptJWTKey: U0JBUElKV1RkV2FuZzkyNjQ1NA==
    # AccessToken过期时间-5分钟-5*60(秒为单位)
    accessTokenExpireTime: 999999
    # RefreshToken过期时间-30分钟-30*60(秒为单位)
    refreshTokenExpireTime: 3600
    # Shiro缓存过期时间-5分钟-5*60(秒为单位)(一般设置与AccessToken过期时间一致)
    shiroCacheExpireTime: 1800

  swagger:
    title: MIX服务
    description: MIX服务接口文档
    base-packages: cn.darkjrong.mix.controller
    version: 1.0
    license: Apache License, Version 2.0
    license-url: https://www.apache.org/licenses/LICENSE-2.0.html
    terms-of-service-url: https://www.apache.org/licenses/LICENSE-2.0.html
    base-path: /**
    contact:
      name: 贾荣
      email: 852203465@qq.com

  # 白名单配置
  whitelist:
    urls:
      - /v3/api-docs
      - /webjars/**
      - /swagger-resources/**
      - /swagger-ui.html
      - /doc.html
      - /auth/**

# mybatis-plus 配置
mybatis-plus:
  global-config:
    db-config:
      # 主键ID 生成策略
      id-type: assign_id
  configuration:
    # 是否开启自动驼峰命名规则（camel case）映射
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:/mappers/**/*.xml

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql




























